### ISSUE TITLE
Not available for new R (4.0.2)

### ISSUE THREAD

**Issue by gyzsolt91** [CharlesJB/ENCODExplorer#54]
Hi,
 I tried to install package, but in the conventional way (with BiocManager::install() ) downloading got stuck and operation got aborted. After that I tried install from binary file, but I got the following warning message:
"package ‘~/Downloads/ENCODExplorer_2.14.0.tar’ is not available (for R version 4.0.2)"
Will package updated to be compatible with newest version of R?

Thanks in advance!
Zsolt

**Comment by ericfournier2** [comment]
Hello Zsolt,

"download got stuck" sounds like a networking issue, either on your end or Bioconductor's. Have you tried reinstalling since you got that error? It's working here for me.

There is no reason why metagene should not be compatible with R 4.0.2, I'm not completely certain of how/when binary packages are made available, but you can always reinstall from source, by cloning this repository and doing install.packages("folder/where/you/unpacked/source", type="source", repos=NULL)

Hope this helps,
-Eric

**Comment by jianhong** [comment]
Dear Eric,

When will it be fixed for the develop version and release version of binary building? It got error since the release of Bioconductor 3.13.

**Comment by ericfournier2** [comment]
Hello @jianhong , we're working on fixing the issue. You can track our progress in Issue #56.
